import type { WordEntry } from '../types';

export const folkAndOddities: WordEntry[] = [
  { word: 'agelast', definition: 'one who never laughs' },
  { word: 'absquatulate', definition: 'to depart abruptly' },
  { word: 'balter', definition: 'to dance clumsily' },
  { word: 'borborygmus', definition: 'the rumbling of an empty stomach' },
  { word: 'cachinnate', definition: 'to laugh loudly and immoderately' },
  { word: 'callipygian', definition: 'having finely shaped buttocks' },
  { word: 'clinquant', definition: 'glittering as with gold' },
  { word: 'defenestrate', definition: 'to throw out of a window' },
  { word: 'eldritch', definition: 'weird and sinister' },
  { word: 'eleemosynary', definition: 'relating to charity or alms' },
  { word: 'ensorcell', definition: 'to enchant or bewitch' },
  { word: 'famulus', definition: 'an attendant to a scholar or mage' },
  { word: 'fatuous', definition: 'silly and self-satisfied' },
  { word: 'floccinaucinihilipilification', definition: 'the act of judging worthless' },
  { word: 'gallimaufry', definition: 'a jumbled medley' },
  { word: 'gongoozler', definition: 'an idle watcher of canals' },
  { word: 'hoary', definition: 'grey or white with age' },
  { word: 'inglenook', definition: 'a snug corner beside a hearth' },
  { word: 'jentacular', definition: 'pertaining to breakfast' },
  { word: 'lucubrate', definition: 'to study long by lamplight' },
  { word: 'macilent', definition: 'lean and wasted' },
  { word: 'nefandous', definition: 'too dreadful to be spoken' },
  { word: 'pandiculation', definition: 'a full-body stretch on waking' },
  { word: 'scintilla', definition: 'a faint trace or spark' },
  { word: 'tatterdemalion', definition: 'a person in ragged clothing' },
  { word: 'tenebrous', definition: 'dark, shadowy, and gloomy' },
  { word: 'tergiversate', definition: 'to abandon a cause one held' },
  { word: 'thaumaturgy', definition: 'the working of wonders' },
  { word: 'usufruct', definition: 'the right to enjoy what belongs to another' },
  { word: 'widdershins', definition: 'in a counterclockwise course' },
  { word: 'winsome', definition: 'sweetly charming' },
  { word: 'xenial', definition: 'warmly hospitable to guests' },
  { word: 'zugzwang', definition: 'a spot where every move worsens things' },
  { word: 'lissome', definition: 'lithe and supple' },
  { word: 'peripatetic', definition: 'wandering from place to place' },
  { word: 'quaquaversal', definition: 'pointing every which way' },
  { word: 'resistentialism', definition: 'the seeming spite of inanimate things' },
  { word: 'selcouth', definition: 'strange yet wondrous' },
  { word: 'wamble', definition: 'to feel queasy; to move unsteadily' },
  { word: 'cynosure', definition: 'the center of all attention' },
  { word: 'desuetude', definition: 'a state of disuse' },
  { word: 'gowpen', definition: 'the hollow of two cupped hands' },
  { word: 'rambunctious', definition: 'boisterous and unruly' },
  { word: 'mataeotechny', definition: 'an unprofitable or useless art' },
  { word: 'solivagant', definition: 'wandering alone' },
  { word: 'adumbrate', definition: 'to foreshadow faintly' },
  { word: 'febricity', definition: 'the state of having a fever' },
  { word: 'pogonotrophy', definition: 'the cultivation of a beard' },
];